# Generated by Django 3.1.2 on 2021-01-23 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_image', models.ImageField(blank=True, default='noimage2.jpg', null=True, upload_to='images/', verbose_name='プロフィール画像')),
                ('p_content', models.TextField(blank=True, null=True, verbose_name='自己紹介文')),
                ('p_place', models.CharField(blank=True, max_length=40, null=True, verbose_name='居住地')),
                ('p_hobby', models.TextField(blank=True, null=True, verbose_name='趣味')),
                ('p_show', models.BooleanField(default=False, verbose_name='公開非公開(チェックを入れると他の会員様にプロフィールが公開されます。)')),
                ('p_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_owner', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
