# Generated by Django 3.1.2 on 2021-01-23 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210123_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_owner', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
