# Generated by Django 3.1.2 on 2021-01-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210124_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='p_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='p_hobby',
            new_name='hobby',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='p_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='p_place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='p_show',
            new_name='show',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='p_owner',
            new_name='user',
        ),
    ]
