# Generated by Django 3.1.2 on 2021-01-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210124_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='content',
            field=models.TextField(blank=True, default='None', null=True, verbose_name='自己紹介文'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobby',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='趣味'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='place',
            field=models.CharField(blank=True, default='None', max_length=40, null=True, verbose_name='居住地'),
        ),
    ]
