# Generated by Django 3.1.2 on 2021-01-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210124_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='noimage2.png', null=True, upload_to='images/', verbose_name='プロフィール画像'),
        ),
    ]
