# Generated by Django 3.1.2 on 2021-01-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='content',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='place',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show',
        ),
    ]
