# Generated by Django 3.1.2 on 2021-01-28 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_blacklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackList',
        ),
    ]
