# Generated by Django 3.1.2 on 2021-03-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_delete_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth',
            field=models.DateField(null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=40, null=True, verbose_name='本名'),
        ),
    ]
