# Generated by Django 3.1.2 on 2021-04-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avengers',
            name='relate',
            field=models.ManyToManyField(blank=True, related_name='_avengers_relate_+', to='avengers.Avengers', verbose_name='関連'),
        ),
        migrations.AlterField(
            model_name='avengers',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag', to='avengers.Tag', verbose_name='タグ'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='relate',
            field=models.ManyToManyField(blank=True, related_name='_experiences_relate_+', to='avengers.Experiences', verbose_name='関連'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag', to='avengers.Tag2', verbose_name='タグ'),
        ),
    ]
