# Generated by Django 3.1.2 on 2020-12-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avengers',
            name='media1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='動画,音声1'),
        ),
        migrations.AddField(
            model_name='avengers',
            name='media2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='動画,音声2'),
        ),
        migrations.AddField(
            model_name='avengers',
            name='media3',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='動画,音声3'),
        ),
    ]
