# Generated by Django 3.1.2 on 2021-04-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0002_auto_20210408_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avengers',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag', to='avengers.Tag', verbose_name='タグ(追加してほしいタグありましたら問い合わせお願いします。)'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag', to='avengers.Tag2', verbose_name='タグ(追加してほしいタグありましたら問い合わせお願いします。)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tag', to='avengers.Tag3', verbose_name='タグ(追加してほしいタグありましたら問い合わせお願いします。)'),
        ),
    ]
