# Generated by Django 3.1.2 on 2021-04-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0002_noticeread_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeread',
            name='notice',
        ),
        migrations.RemoveField(
            model_name='noticeread',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='NoticeRead',
        ),
    ]
