# Generated by Django 3.1.2 on 2020-12-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0003_auto_20201228_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='avengers',
            name='group',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='所属団体名(未記入でも可)'),
        ),
        migrations.AlterField(
            model_name='avengers',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='被害内容詳細(職場いじめ、パワハラ等)'),
        ),
    ]
