# Generated by Django 3.1.2 on 2021-04-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0004_auto_20210409_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='avengerslog',
            name='user_num',
            field=models.IntegerField(default=0, verbose_name='投稿者ID'),
        ),
        migrations.AddField(
            model_name='experienceslog',
            name='user_num',
            field=models.IntegerField(default=0, verbose_name='投稿者ID'),
        ),
    ]
