# Generated by Django 3.1.2 on 2020-12-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='avengers',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='いいね'),
        ),
    ]
