# Generated by Django 3.1.2 on 2021-04-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0006_notice_noticeread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoticeRead',
        ),
    ]
