# Generated by Django 3.1.2 on 2021-04-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0010_auto_20210407_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avengers',
            name='relate',
            field=models.ManyToManyField(blank=True, related_name='_avengers_relate_+', to='avengers.Avengers', verbose_name='関連'),
        ),
        migrations.AlterField(
            model_name='avengers',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='_avengers_tags_+', to='avengers.Avengers', verbose_name='タグ'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='relate',
            field=models.ManyToManyField(blank=True, related_name='_experiences_relate_+', to='avengers.Experiences', verbose_name='関連'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='_experiences_tag_+', to='avengers.Experiences', verbose_name='タグ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='_post_tag_+', to='avengers.Post', verbose_name='タグ'),
        ),
    ]
