# Generated by Django 3.1.2 on 2020-12-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0010_delete_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
