# Generated by Django 3.1.2 on 2020-12-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0013_auto_20201231_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default='名無し', max_length=200),
        ),
    ]
