# Generated by Django 3.1.2 on 2021-01-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0014_comment_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
