# Generated by Django 3.1.2 on 2021-01-06 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avengers', '0023_auto_20210105_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='avengers',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
