# Generated by Django 3.1.2 on 2021-01-06 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avengers', '0024_avengers_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avengers',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL, verbose_name='いいね'),
        ),
    ]
