# Generated by Django 3.1.2 on 2021-01-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0025_auto_20210106_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avengers',
            name='like',
        ),
        migrations.AddField(
            model_name='avengers',
            name='like',
            field=models.IntegerField(default=0, verbose_name='いいね'),
        ),
    ]
