# Generated by Django 3.1.2 on 2021-01-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0027_auto_20210106_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avengers',
            name='media3',
        ),
        migrations.RemoveField(
            model_name='avengers',
            name='media4',
        ),
        migrations.RemoveField(
            model_name='avengers',
            name='media5',
        ),
        migrations.RemoveField(
            model_name='avengers',
            name='media6',
        ),
        migrations.RemoveField(
            model_name='avengers',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='avengers',
            name='photo3',
        ),
        migrations.AlterField(
            model_name='avengers',
            name='media1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='音声'),
        ),
        migrations.AlterField(
            model_name='avengers',
            name='media2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='動画'),
        ),
        migrations.AlterField(
            model_name='avengers',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真'),
        ),
    ]
