# Generated by Django 3.1.2 on 2021-01-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0028_auto_20210107_1727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
