# Generated by Django 3.1.2 on 2021-01-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0029_delete_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avator', models.ImageField(upload_to='images/', verbose_name='アバター')),
            ],
        ),
    ]
