# Generated by Django 3.1.2 on 2021-01-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0030_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
