# Generated by Django 3.1.2 on 2021-01-08 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0032_avator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avator',
            name='user',
        ),
    ]
