# Generated by Django 3.1.2 on 2021-01-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0033_remove_avator_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avator',
        ),
    ]
