# Generated by Django 3.1.2 on 2021-01-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0035_avator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avator',
            options={},
        ),
        migrations.RemoveField(
            model_name='avator',
            name='user',
        ),
    ]
