# Generated by Django 3.1.2 on 2021-01-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0037_auto_20210108_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
