# Generated by Django 3.1.2 on 2021-01-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0040_remove_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avengers',
            name='group',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='所属団体名・加害者名(未記入でも可)'),
        ),
        migrations.AlterField(
            model_name='avengers',
            name='title',
            field=models.CharField(max_length=40, verbose_name='被害内容'),
        ),
    ]
