# Generated by Django 3.1.2 on 2021-01-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0041_auto_20210111_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
