# Generated by Django 3.1.2 on 2021-01-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0043_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
