# Generated by Django 3.1.2 on 2021-01-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0044_remove_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
