# Generated by Django 3.1.2 on 2021-01-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0046_friend_good_group_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='message',
        ),
        migrations.RemoveField(
            model_name='good',
            name='user',
        ),
        migrations.RemoveField(
            model_name='group',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Good',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
