# Generated by Django 3.1.2 on 2021-01-14 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0048_friend_good_group_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
