# Generated by Django 3.1.2 on 2021-01-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0050_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='show',
            field=models.BooleanField(default=False, verbose_name='公開非公開(チェックを入れると他の会員様にプロフィールが公開されます。)'),
        ),
    ]
