# Generated by Django 3.1.2 on 2021-01-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0051_auto_20210115_1500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
