# Generated by Django 3.1.2 on 2021-01-16 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avengers', '0053_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='avengers',
            name='good_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='good_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_owner', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.DeleteModel(
            name='Good',
        ),
    ]
