# Generated by Django 3.1.2 on 2021-01-16 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0055_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='avengers',
        ),
        migrations.RemoveField(
            model_name='good',
            name='comment',
        ),
    ]
