# Generated by Django 3.1.2 on 2021-01-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0058_auto_20210116_2135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Good3',
        ),
    ]
