# Generated by Django 3.1.2 on 2021-01-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0059_delete_good3'),
    ]

    operations = [
        migrations.AddField(
            model_name='avengers',
            name='favorite',
            field=models.BooleanField(default='False', verbose_name='お気に入り(チェックを入れ承認するとお気に入り登録されます。)'),
        ),
    ]
