# Generated by Django 3.1.2 on 2021-01-18 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0061_auto_20210118_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
