# Generated by Django 3.1.2 on 2021-01-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0063_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
