# Generated by Django 3.1.2 on 2021-01-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0065_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='avengers',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
