# Generated by Django 3.1.2 on 2021-01-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0067_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='favorite',
        ),
        migrations.AddField(
            model_name='favorite',
            name='favorite',
            field=models.ManyToManyField(blank=True, to='avengers.Avengers', verbose_name='保存した記事'),
        ),
    ]
