# Generated by Django 3.1.2 on 2021-01-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0068_auto_20210118_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
