# Generated by Django 3.1.2 on 2021-01-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0070_auto_20210119_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='お気に入り設定'),
        ),
    ]
