# Generated by Django 3.1.2 on 2021-01-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0071_auto_20210119_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avengers',
            name='is_favorite',
        ),
    ]
