# Generated by Django 3.1.2 on 2021-01-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0072_remove_avengers_is_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name_plural': 'Favorite'},
        ),
    ]
