# Generated by Django 3.1.2 on 2021-01-19 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0073_auto_20210119_0026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
