# Generated by Django 3.1.2 on 2021-01-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0077_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
