# Generated by Django 3.1.2 on 2021-01-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0080_imageupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
