# Generated by Django 3.1.2 on 2021-01-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0082_imageupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-m_pub_date',)},
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='group',
            new_name='f_group',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='owner',
            new_name='f_owner',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='user',
            new_name='f_user',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='owner',
            new_name='g_owner',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='title',
            new_name='g_title',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='m_content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='good_count',
            new_name='m_good_count',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='group',
            new_name='m_group',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='owner',
            new_name='m_owner',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='pub_date',
            new_name='m_pub_date',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='share_count',
            new_name='m_share_count',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='share_id',
            new_name='m_share_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='content',
            new_name='p_content',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='group',
            new_name='p_group',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='hobby',
            new_name='p_hobby',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='p_image',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='owner',
            new_name='p_owner',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='place',
            new_name='p_place',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='show',
            new_name='p_show',
        ),
    ]
