# Generated by Django 3.1.2 on 2021-01-21 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avengers', '0084_auto_20210121_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_content', models.TextField(max_length=1000)),
                ('m_share_id', models.IntegerField(default=-1)),
                ('m_good_count', models.IntegerField(default=0)),
                ('m_share_count', models.IntegerField(default=0)),
                ('m_pub_date', models.DateTimeField(auto_now_add=True)),
                ('m_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.group')),
                ('m_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.userprofile')),
                ('m_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-m_pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.message')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.group')),
                ('f_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.userprofile')),
                ('f_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_owner', to=settings.AUTH_USER_MODEL)),
                ('f_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='コメント内容')),
                ('good_count', models.IntegerField(default=0)),
                ('c_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.userprofile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avengers.comment', verbose_name='親コメント')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.avengers', verbose_name='対象記事')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
