# Generated by Django 3.1.2 on 2021-01-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0085_comment_friend_good_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='c_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='usericon'),
        ),
    ]
