# Generated by Django 3.1.2 on 2021-01-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0086_auto_20210121_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='f_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='usericon'),
        ),
        migrations.AlterField(
            model_name='message',
            name='m_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='usericon'),
        ),
    ]
