# Generated by Django 3.1.2 on 2021-01-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0087_auto_20210121_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
