# Generated by Django 3.1.2 on 2021-01-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0089_good3'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_good_count',
            field=models.IntegerField(default=0),
        ),
    ]
