# Generated by Django 3.1.2 on 2021-01-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0090_comment_reply_good_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='p_image',
            field=models.ImageField(blank=True, default='noimage2.jpg', null=True, upload_to='images/', verbose_name='プロフィール画像'),
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
