# Generated by Django 3.1.2 on 2021-01-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0091_auto_20210123_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='c_image',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='f_image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='m_image',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
