# Generated by Django 3.1.2 on 2021-01-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0092_auto_20210123_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='message',
        ),
        migrations.RemoveField(
            model_name='good',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='group',
            name='g_owner',
        ),
        migrations.RemoveField(
            model_name='message',
            name='m_group',
        ),
        migrations.RemoveField(
            model_name='message',
            name='m_owner',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Good',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
