# Generated by Django 3.1.2 on 2021-01-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0097_auto_20210125_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_c',
            field=models.IntegerField(default=0),
        ),
    ]
