# Generated by Django 3.1.2 on 2021-01-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0098_comment_comment_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='avengers',
            name='view_number',
            field=models.IntegerField(default=0),
        ),
    ]
