# Generated by Django 3.1.2 on 2021-01-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0099_avengers_view_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avengers',
            name='view_number',
        ),
    ]
