# Generated by Django 3.1.2 on 2021-01-27 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0100_remove_avengers_view_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='スレッド主')),
                ('content', models.TextField(blank=True, null=True, verbose_name='スレッド内容')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.post', verbose_name='通報されたスレッド')),
            ],
        ),
        migrations.CreateModel(
            name='Report2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='コメント主')),
                ('content', models.TextField(blank=True, null=True, verbose_name='コメント内容')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.comment', verbose_name='通報されたコメント')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='投稿主')),
                ('title', models.CharField(max_length=40, verbose_name='被害内容')),
                ('group', models.CharField(blank=True, max_length=40, null=True, verbose_name='企業名・加害者名')),
                ('content', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真')),
                ('media1', models.FileField(blank=True, null=True, upload_to='', verbose_name='音声')),
                ('media2', models.FileField(blank=True, null=True, upload_to='', verbose_name='動画')),
                ('number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('reported_date', models.DateTimeField(auto_now_add=True, verbose_name='通報日時')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.avengers', verbose_name='通報された投稿')),
            ],
        ),
    ]
