# Generated by Django 3.1.2 on 2021-01-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0101_report_report2_report3'),
    ]

    operations = [
        migrations.AddField(
            model_name='report2',
            name='number1',
            field=models.IntegerField(default=0, verbose_name='投稿id'),
        ),
        migrations.AddField(
            model_name='report2',
            name='number2',
            field=models.IntegerField(default=0, verbose_name='コメントid'),
        ),
    ]
