# Generated by Django 3.1.2 on 2021-01-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0102_auto_20210127_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='report3',
            name='number',
            field=models.IntegerField(default=0, verbose_name='スレッドid'),
        ),
    ]
