# Generated by Django 3.1.2 on 2021-01-28 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0105_blacklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackList',
        ),
    ]
