# Generated by Django 3.1.2 on 2021-01-28 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0107_blacklist_blacksubscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacksubscribe',
            name='black',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.blacklist'),
        ),
    ]
