# Generated by Django 3.1.2 on 2021-01-28 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0108_auto_20210128_1057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlackSubscribe',
        ),
    ]
