# Generated by Django 3.1.2 on 2021-01-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0110_auto_20210128_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avengers',
            name='media1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='音声'),
        ),
        migrations.AlterField(
            model_name='avengers',
            name='media2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='動画'),
        ),
        migrations.AlterField(
            model_name='avengers',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真'),
        ),
    ]
