# Generated by Django 3.1.2 on 2021-01-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0112_avengerslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='avengerslog',
            name='number',
            field=models.IntegerField(default=0, verbose_name='整理番号'),
        ),
    ]
