# Generated by Django 3.1.2 on 2021-01-29 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0114_dm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='メッセージ送信者')),
                ('user_id', models.IntegerField(default=0, verbose_name='id')),
                ('content', models.TextField(blank=True, null=True, verbose_name='DM内容')),
                ('number', models.IntegerField(default=0, verbose_name='DMid')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.dm', verbose_name='通報されたDM')),
            ],
        ),
    ]
