# Generated by Django 3.1.2 on 2021-01-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0115_report4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report1_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='投稿主')),
                ('user_id', models.IntegerField(default=0, verbose_name='id')),
                ('title', models.CharField(max_length=40, verbose_name='被害内容')),
                ('group', models.CharField(blank=True, max_length=40, null=True, verbose_name='企業名・加害者名')),
                ('content', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真')),
                ('media1', models.FileField(blank=True, null=True, upload_to='', verbose_name='音声')),
                ('media2', models.FileField(blank=True, null=True, upload_to='', verbose_name='動画')),
                ('number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('reported_date', models.DateTimeField(auto_now_add=True, verbose_name='通報日時')),
            ],
        ),
        migrations.CreateModel(
            name='Report2_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='コメント主')),
                ('user_id', models.IntegerField(default=0, verbose_name='id')),
                ('content', models.TextField(blank=True, null=True, verbose_name='コメント内容')),
                ('number1', models.IntegerField(default=0, verbose_name='投稿id')),
                ('number2', models.IntegerField(default=0, verbose_name='コメントid')),
            ],
        ),
        migrations.CreateModel(
            name='Report3_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='スレッド主')),
                ('user_id', models.IntegerField(default=0, verbose_name='id')),
                ('content', models.TextField(blank=True, null=True, verbose_name='スレッド内容')),
                ('number', models.IntegerField(default=0, verbose_name='スレッドid')),
            ],
        ),
        migrations.CreateModel(
            name='Report4_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='メッセージ送信者')),
                ('user_id', models.IntegerField(default=0, verbose_name='id')),
                ('content', models.TextField(blank=True, null=True, verbose_name='DM内容')),
                ('number', models.IntegerField(default=0, verbose_name='DMid')),
            ],
        ),
    ]
