# Generated by Django 3.1.2 on 2021-01-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0116_report1_1_report2_1_report3_1_report4_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='good3',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='good3',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='report2',
            name='report',
        ),
        migrations.DeleteModel(
            name='Report2_1',
        ),
        migrations.RemoveField(
            model_name='report3',
            name='report',
        ),
        migrations.DeleteModel(
            name='Report3_1',
        ),
        migrations.RemoveField(
            model_name='report4',
            name='report',
        ),
        migrations.DeleteModel(
            name='Report4_1',
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_date',
            field=models.DateTimeField(auto_now=True, verbose_name='通報日時'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Good3',
        ),
        migrations.DeleteModel(
            name='Report2',
        ),
        migrations.DeleteModel(
            name='Report3',
        ),
        migrations.DeleteModel(
            name='Report4',
        ),
    ]
