# Generated by Django 3.1.2 on 2021-01-30 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avengers', '0117_auto_20210130_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='コメント内容')),
                ('good_count', models.IntegerField(default=0)),
                ('reply_good_count', models.IntegerField(default=0)),
                ('comment_c', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='投稿日時')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avengers.comment', verbose_name='親コメント')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.avengers', verbose_name='対象記事')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report2_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='コメント主')),
                ('user_id', models.IntegerField(default=0, verbose_name='id')),
                ('content', models.TextField(blank=True, null=True, verbose_name='コメント内容')),
                ('number1', models.IntegerField(default=0, verbose_name='投稿id')),
                ('number2', models.IntegerField(default=0, verbose_name='コメントid')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='投稿日時')),
                ('reported_at', models.DateTimeField(auto_now=True, verbose_name='通報日時')),
            ],
        ),
        migrations.CreateModel(
            name='Report3_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='スレッド主')),
                ('user_id', models.IntegerField(default=0, verbose_name='id')),
                ('content', models.TextField(blank=True, null=True, verbose_name='スレッド内容')),
                ('number', models.IntegerField(default=0, verbose_name='スレッドid')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='投稿日時')),
                ('reported_at', models.DateTimeField(auto_now=True, verbose_name='通報日時')),
            ],
        ),
        migrations.CreateModel(
            name='Report4_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='メッセージ送信者')),
                ('user_id', models.IntegerField(default=0, verbose_name='id')),
                ('content', models.TextField(blank=True, null=True, verbose_name='DM内容')),
                ('number', models.IntegerField(default=0, verbose_name='DMid')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='投稿日時')),
                ('reported_at', models.DateTimeField(auto_now=True, verbose_name='通報日時')),
            ],
        ),
        migrations.CreateModel(
            name='Report4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='メッセージ送信者')),
                ('user_id', models.IntegerField(default=0, verbose_name='id')),
                ('content', models.TextField(blank=True, null=True, verbose_name='DM内容')),
                ('number', models.IntegerField(default=0, verbose_name='DMid')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='通報日時')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.dm', verbose_name='通報されたDM')),
            ],
        ),
        migrations.CreateModel(
            name='Report3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='スレッド主')),
                ('user_id', models.IntegerField(default=0, verbose_name='id')),
                ('content', models.TextField(blank=True, null=True, verbose_name='スレッド内容')),
                ('number', models.IntegerField(default=0, verbose_name='スレッドid')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='通報日時')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.post', verbose_name='通報されたスレッド')),
            ],
        ),
        migrations.CreateModel(
            name='Report2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='コメント主')),
                ('user_id', models.IntegerField(default=0, verbose_name='id')),
                ('content', models.TextField(blank=True, null=True, verbose_name='コメント内容')),
                ('number1', models.IntegerField(default=0, verbose_name='投稿id')),
                ('number2', models.IntegerField(default=0, verbose_name='コメントid')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='通報日時')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.comment', verbose_name='通報されたコメント')),
            ],
        ),
        migrations.CreateModel(
            name='Good3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.comment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_owner3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
