# Generated by Django 3.1.2 on 2021-01-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0118_comment_good3_report2_report2_1_report3_report3_1_report4_report4_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report1_1',
            name='created_at',
            field=models.DateTimeField(verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='report2_1',
            name='created_at',
            field=models.DateTimeField(verbose_name='投稿日時'),
        ),
        migrations.AlterField(
            model_name='report3_1',
            name='created_at',
            field=models.DateTimeField(verbose_name='投稿日時'),
        ),
        migrations.AlterField(
            model_name='report4_1',
            name='created_at',
            field=models.DateTimeField(verbose_name='投稿日時'),
        ),
    ]
