# Generated by Django 3.1.2 on 2021-01-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0121_auto_20210130_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAllRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='ユーザー名')),
                ('user_id', models.IntegerField(default=0)),
                ('user_email', models.TextField(blank=True, null=True, verbose_name='アドレス')),
                ('login_time', models.DateTimeField(blank=True, null=True, verbose_name='ログイン時刻')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='ログアウト時刻')),
            ],
        ),
    ]
