# Generated by Django 3.1.2 on 2021-01-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0122_attendanceallrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='ユーザー')),
                ('user_id', models.IntegerField(default=0, verbose_name='ユーザーID')),
                ('is_reported', models.IntegerField(default=0, verbose_name='通報された回数')),
            ],
        ),
    ]
