# Generated by Django 3.1.2 on 2021-01-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0123_allblacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceallrecord',
            name='login_time',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ログイン時刻'),
        ),
        migrations.AlterField(
            model_name='attendanceallrecord',
            name='logout_time',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ログアウト時刻'),
        ),
        migrations.AlterField(
            model_name='report1_1',
            name='created_at',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='report1_1',
            name='reported_date',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='通報日時'),
        ),
        migrations.AlterField(
            model_name='report2_1',
            name='created_at',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='投稿日時'),
        ),
        migrations.AlterField(
            model_name='report2_1',
            name='reported_at',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='通報日時'),
        ),
        migrations.AlterField(
            model_name='report3_1',
            name='created_at',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='投稿日時'),
        ),
        migrations.AlterField(
            model_name='report3_1',
            name='reported_at',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='通報日時'),
        ),
        migrations.AlterField(
            model_name='report4_1',
            name='created_at',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='投稿日時'),
        ),
        migrations.AlterField(
            model_name='report4_1',
            name='reported_at',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='通報日時'),
        ),
    ]
