# Generated by Django 3.1.2 on 2021-02-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0125_comment2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(verbose_name='投稿日時'),
        ),
    ]
