# Generated by Django 3.1.2 on 2021-02-09 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0126_auto_20210209_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='report1_1',
            name='owner',
            field=models.CharField(default='No name', max_length=40, verbose_name='通報者'),
        ),
        migrations.AddField(
            model_name='report1_1',
            name='owner_id',
            field=models.IntegerField(default=0, verbose_name='通報者ID'),
        ),
        migrations.AddField(
            model_name='report2_1',
            name='owner',
            field=models.CharField(default='No name', max_length=40, verbose_name='通報者'),
        ),
        migrations.AddField(
            model_name='report2_1',
            name='owner_id',
            field=models.IntegerField(default=0, verbose_name='通報者ID'),
        ),
        migrations.AddField(
            model_name='report3_1',
            name='owner',
            field=models.CharField(default='No name', max_length=40, verbose_name='通報者'),
        ),
        migrations.AddField(
            model_name='report3_1',
            name='owner_id',
            field=models.IntegerField(default=0, verbose_name='通報者ID'),
        ),
        migrations.AddField(
            model_name='report4_1',
            name='owner',
            field=models.CharField(default='No name', max_length=40, verbose_name='通報者'),
        ),
        migrations.AddField(
            model_name='report4_1',
            name='owner_id',
            field=models.IntegerField(default=0, verbose_name='通報者ID'),
        ),
        migrations.CreateModel(
            name='Report5_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='コメントユーザー')),
                ('user_id', models.IntegerField(default=0, verbose_name='id')),
                ('content', models.TextField(blank=True, null=True, verbose_name='コメント内容')),
                ('number', models.IntegerField(default=0, verbose_name='コメントID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='通報日時')),
                ('owner', models.CharField(max_length=40, verbose_name='通報者')),
                ('owner_id', models.IntegerField(default=0, verbose_name='通報者ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.comment2', verbose_name='通報されたコメント')),
            ],
        ),
        migrations.CreateModel(
            name='Report5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='コメントユーザー')),
                ('user_id', models.IntegerField(default=0, verbose_name='id')),
                ('content', models.TextField(blank=True, null=True, verbose_name='コメント内容')),
                ('number', models.IntegerField(default=0, verbose_name='コメントID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='通報日時')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.comment2', verbose_name='通報されたコメント')),
            ],
        ),
    ]
