# Generated by Django 3.1.2 on 2021-02-09 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0127_auto_20210209_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='report5_1',
            name='reported_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 12, 26, 26, 247316, tzinfo=utc)),
        ),
    ]
