# Generated by Django 3.1.2 on 2021-02-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0130_auto_20210209_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment2',
            name='date_posted',
            field=models.DateTimeField(verbose_name='コメント日時'),
        ),
    ]
