# Generated by Django 3.1.2 on 2021-02-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0131_auto_20210209_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report5_1',
            name='created_at',
            field=models.DateTimeField(verbose_name='投稿日時'),
        ),
        migrations.AlterField(
            model_name='report5_1',
            name='reported_at',
            field=models.DateTimeField(verbose_name='通報日時'),
        ),
    ]
