# Generated by Django 3.1.2 on 2021-02-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0133_good4'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment2',
            name='good_count',
            field=models.IntegerField(default=0),
        ),
    ]
