# Generated by Django 3.1.2 on 2021-02-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0135_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='posted',
            field=models.DateTimeField(verbose_name='通知日時'),
        ),
    ]
