# Generated by Django 3.1.2 on 2021-02-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0136_auto_20210226_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='通知日時'),
        ),
    ]
