# Generated by Django 3.1.2 on 2021-02-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0137_auto_20210226_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='user',
        ),
    ]
