# Generated by Django 3.1.2 on 2021-02-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0138_remove_notice_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='owner',
            new_name='user',
        ),
    ]
