# Generated by Django 3.1.2 on 2021-02-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0139_auto_20210226_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm',
            name='content',
            field=models.TextField(max_length=250),
        ),
    ]
