# Generated by Django 3.1.2 on 2021-03-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0142_remove_comment_reply_good_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='avengers',
            name='is_reported',
            field=models.CharField(default='', max_length=10, verbose_name='通報状態'),
        ),
    ]
