# Generated by Django 3.1.2 on 2021-03-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0143_avengers_is_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_reported',
            field=models.CharField(default='', max_length=10, verbose_name='通報状態'),
        ),
        migrations.AddField(
            model_name='comment2',
            name='is_reported',
            field=models.CharField(default='', max_length=10, verbose_name='通報状態'),
        ),
        migrations.AddField(
            model_name='dm',
            name='is_reported',
            field=models.CharField(default='', max_length=10, verbose_name='通報状態'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_reported',
            field=models.CharField(default='', max_length=10, verbose_name='通報状態'),
        ),
    ]
