# Generated by Django 3.1.2 on 2021-03-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0144_auto_20210307_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='avengers',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
