# Generated by Django 3.1.2 on 2021-03-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0145_avengers_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='View',
        ),
    ]
