# Generated by Django 3.1.2 on 2021-03-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0146_delete_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avengers',
            name='group',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='会社名・加害者名・学校名(未記入でも可)'),
        ),
    ]
