# Generated by Django 3.1.2 on 2021-03-29 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0148_auto_20210329_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiences',
            name='user',
        ),
        migrations.RemoveField(
            model_name='good5',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='good5',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='good6',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='good6',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Comment3',
        ),
        migrations.DeleteModel(
            name='Experiences',
        ),
        migrations.DeleteModel(
            name='Good5',
        ),
        migrations.DeleteModel(
            name='Good6',
        ),
    ]
