# Generated by Django 3.1.2 on 2021-03-29 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0150_auto_20210329_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment3',
            name='post_connected',
        ),
        migrations.AddField(
            model_name='comment3',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avengers.comment3', verbose_name='親コメント'),
        ),
        migrations.AlterField(
            model_name='comment3',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.experiences', verbose_name='対象記事'),
        ),
    ]
