# Generated by Django 3.1.2 on 2021-03-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0151_auto_20210329_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment3',
            old_name='post',
            new_name='post_connected',
        ),
    ]
