# Generated by Django 3.1.2 on 2021-03-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0152_auto_20210329_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment3',
            name='comment_c',
            field=models.IntegerField(default=0),
        ),
    ]
