# Generated by Django 3.1.2 on 2021-03-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0154_auto_20210329_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiences',
            name='comment_c',
        ),
        migrations.AddField(
            model_name='comment3',
            name='comment_c',
            field=models.IntegerField(default=0),
        ),
    ]
