# Generated by Django 3.1.2 on 2021-03-29 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avengers', '0156_auto_20210329_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperiencesLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='被害内容')),
                ('content', models.TextField(blank=True, null=True, verbose_name='被害内容詳細(職場いじめ、パワハラ等)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真')),
                ('video', models.FileField(blank=True, null=True, upload_to='', verbose_name='動画')),
                ('number', models.IntegerField(default=0, verbose_name='整理番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('avengers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.experiences', verbose_name='履歴に記録される投稿')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'ExperiencesLog',
            },
        ),
    ]
