# Generated by Django 3.1.2 on 2021-03-29 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avengers', '0157_experienceslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='good_count',
        ),
        migrations.CreateModel(
            name='Favorite2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='タイトル')),
                ('content', models.TextField(blank=True, null=True, verbose_name='被害内容詳細(職場いじめ、パワハラ等)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像')),
                ('video', models.FileField(blank=True, null=True, upload_to='', verbose_name='動画')),
                ('number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.experiences', verbose_name='保存した記事')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_owner2', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
