# Generated by Django 3.1.2 on 2021-03-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0158_auto_20210330_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiences',
            name='is_reported',
        ),
    ]
