# Generated by Django 3.1.2 on 2021-03-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0159_remove_experiences_is_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report6_1',
            name='report',
        ),
        migrations.RemoveField(
            model_name='report7',
            name='report',
        ),
        migrations.RemoveField(
            model_name='report7_1',
            name='report',
        ),
        migrations.DeleteModel(
            name='Report6',
        ),
        migrations.DeleteModel(
            name='Report6_1',
        ),
        migrations.DeleteModel(
            name='Report7',
        ),
        migrations.DeleteModel(
            name='Report7_1',
        ),
    ]
