# Generated by Django 3.1.2 on 2021-03-30 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0160_auto_20210330_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report7_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='コメントユーザー')),
                ('user_id', models.IntegerField(default=0, verbose_name='id')),
                ('content', models.TextField(blank=True, null=True, verbose_name='コメント内容')),
                ('number', models.IntegerField(default=0, verbose_name='コメントID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='投稿日時')),
                ('reported_at', models.DateTimeField(verbose_name='通報日時')),
                ('owner', models.CharField(max_length=40, verbose_name='通報者')),
                ('owner_id', models.IntegerField(default=0, verbose_name='通報者ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.comment2', verbose_name='通報されたコメント')),
            ],
        ),
        migrations.CreateModel(
            name='Report7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='コメントユーザー')),
                ('user_id', models.IntegerField(default=0, verbose_name='id')),
                ('content', models.TextField(blank=True, null=True, verbose_name='コメント内容')),
                ('number', models.IntegerField(default=0, verbose_name='コメントID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='通報日時')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.comment2', verbose_name='通報されたコメント')),
            ],
        ),
        migrations.CreateModel(
            name='Report6_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='スピーチ投稿者')),
                ('user_id', models.IntegerField(default=0, verbose_name='id')),
                ('title', models.CharField(max_length=40, verbose_name='タイトル')),
                ('content', models.TextField(blank=True, null=True, verbose_name='説明文')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='紹介画像')),
                ('video', models.FileField(upload_to='', verbose_name='スピーチ動画')),
                ('number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='投稿日時')),
                ('reported_at', models.DateTimeField(verbose_name='通報日時')),
                ('owner', models.CharField(max_length=40, verbose_name='通報者')),
                ('owner_id', models.IntegerField(default=0, verbose_name='通報者ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.experiences', verbose_name='通報されたスピーチ')),
            ],
        ),
        migrations.CreateModel(
            name='Report6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='スピーチ投稿者')),
                ('user_id', models.IntegerField(default=0, verbose_name='id')),
                ('title', models.CharField(max_length=40, verbose_name='タイトル')),
                ('content', models.TextField(blank=True, null=True, verbose_name='説明文')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='紹介画像')),
                ('video', models.FileField(upload_to='', verbose_name='スピーチ動画')),
                ('number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='通報日時')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.experiences', verbose_name='通報されたスピーチ')),
            ],
        ),
    ]
