# Generated by Django 3.1.2 on 2021-03-30 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0161_report6_report6_1_report7_report7_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report7',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avengers.comment3', verbose_name='通報されたコメント'),
        ),
    ]
