# Generated by Django 3.1.2 on 2021-04-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0163_auto_20210330_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='動画紹介画像'),
        ),
    ]
