# Generated by Django 3.1.2 on 2021-04-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0164_auto_20210401_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='avengers',
            name='show',
            field=models.BooleanField(default=False, verbose_name='被害記事を公開したい場合こちらのチェックボックスにチェックをお願いします。'),
        ),
    ]
