# Generated by Django 3.1.2 on 2021-04-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0167_noticeread'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeread',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
