# Generated by Django 3.1.2 on 2021-04-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avengers', '0168_noticeread_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeread',
            name='number',
        ),
    ]
