from django.contrib import admin

from .models import Tag, Tag2, Tag3, Avengers, Experiences, Comment, Comment2, Comment3, Notice, NoticeRead, Post, Good, Good2, Good3, Good4, Good5, Good6, Favorite, DM, Report, Report2, Report3, Report4, Report5, Report6, Report7, Report1_1, Report2_1, Report3_1, Report4_1, Report5_1, Report6_1, Report7_1, BlackList, AllBlackList, AvengersLog, AttendanceRecord, AttendanceAllRecord


admin.site.register(Tag)
admin.site.register(Tag2)
admin.site.register(Tag3)
admin.site.register(Avengers)
admin.site.register(Experiences)
admin.site.register(Comment)
admin.site.register(Comment2)
admin.site.register(Comment3)
admin.site.register(Notice)
admin.site.register(NoticeRead)
admin.site.register(Post)
admin.site.register(Good)
admin.site.register(Good2)
admin.site.register(Good3)
admin.site.register(Good4)
admin.site.register(Good5)
admin.site.register(Good6)
admin.site.register(Favorite)
admin.site.register(DM)
admin.site.register(Report)
admin.site.register(Report2)
admin.site.register(Report3)
admin.site.register(Report4)
admin.site.register(Report5)
admin.site.register(Report6)
admin.site.register(Report7)
admin.site.register(Report1_1)
admin.site.register(Report2_1)
admin.site.register(Report3_1)
admin.site.register(Report4_1)
admin.site.register(Report5_1)
admin.site.register(Report6_1)
admin.site.register(Report7_1)
admin.site.register(BlackList)
admin.site.register(AllBlackList)
admin.site.register(AvengersLog)
admin.site.register(AttendanceRecord)
admin.site.register(AttendanceAllRecord)