from django.urls import path

from . import views


app_name = 'avengers'

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('tag_create/', views.TagCreate.as_view(), name="tag_create"),
    path('tag2_create/', views.Tag2Create.as_view(), name="tag2_create"),
    path('tag3_create/', views.Tag3Create.as_view(), name="tag3_create"),
    path('diary_list/', views.DiaryListView.as_view(), name="diary_list"),
    path('diary-detail/<int:pk>/', views.DiaryDetailView.as_view(), name="diary_detail"),
    path('diary-create/', views.DiaryCreateView.as_view(), name="diary_create"),
    path('diary-update/<int:pk>/', views.DiaryUpdateView.as_view(), name="diary_update"),
    path('diary-delete/<int:pk>/', views.DiaryDeleteView.as_view(), name="diary_delete"),
    path('experiences_list/', views.ExperiencesListView.as_view(), name="experiences_list"),
    path('experiences-detail/<int:pk>/', views.ExperiencesDetailView.as_view(), name="experiences_detail"),
    path('experiences-create/', views.ExperiencesCreateView.as_view(), name="experiences_create"),
    path('experiences-update/<int:pk>/', views.ExperiencesUpdateView.as_view(), name="experiences_update"),
    path('experiences-delete/<int:pk>/', views.ExperiencesDeleteView.as_view(), name="experiences_delete"),
    path('notice_list/', views.NoticeListView.as_view(), name="notice_list"),
    path('notice_create/', views.NoticeCreateView.as_view(), name="notice_create"),
    path('notice_detail/<int:pk>/', views.NoticeDetailView.as_view(), name="notice_detail"),
    path('notice_read/<int:pk>/', views.noticeread, name='notice_read'),
    path('accuse_list/', views.AccuseListView.as_view(), name="accuse_list"),
    path('accuse_video_only/', views.AccuseListViewMovieOnly.as_view(), name="accuse_video"),
    path('accuse_sound_only/', views.AccuseListViewSoundOnly.as_view(), name="accuse_sound"),
    path('accuse_photo_only/', views.AccuseListViewPhotoOnly.as_view(), name="accuse_photo"),
    path('accuse_good_descending/', views.AccuseListViewGoodDescending.as_view(), name="accuse_good_descending"),
    path('accuse_good_ascending/', views.AccuseListViewGoodAscending.as_view(), name="accuse_good_ascending"),
    path('accuse_old/', views.AccuseListViewOld.as_view(), name="accuse_old"),
    path('accuse_new/', views.AccuseListViewNew.as_view(), name="accuse_new"),
    path('accuse_detail/<int:pk>/', views.AccuseDetailView.as_view(), name="accuse_detail"),
    path('accuse_delete/<int:pk>/', views.AccuseDeleteView.as_view(), name="accuse_delete"),
    path('tag/<int:pk>/', views.TagDetail.as_view(), name='tag_detail'),
    path('present_list/', views.PresentListView.as_view(), name="present_list"),
    path('present_good_descending/', views.PresentListViewGoodDescending.as_view(), name="present_good_descending"),
    path('present_good_ascending/', views.PresentListViewGoodAscending.as_view(), name="present_good_ascending"),
    path('present_old/', views.PresentListViewOld.as_view(), name="present_old"),
    path('present_new/', views.PresentListViewNew.as_view(), name="present_new"),
    path('present_detail/<int:pk>/', views.PresentDetailView.as_view(), name="present_detail"),
    path('present_delete/<int:pk>/', views.PresentDeleteView.as_view(), name="present_delete"),
    path('tag2/<int:pk>/', views.TagDetail2.as_view(), name='tag_detail2'),
    path('favorite_list/', views.FavoriteView.as_view(), name="favorite"),
    path('see_favorite/<int:pk>/', views.seefavorite, name="see_favorite"),
    path('favorite_delete/<int:pk>/', views.FavoriteDeleteView.as_view(), name="favorite_delete"),
    path('add_favorite/<int:post_pk>/', views.add_favorite, name="add_favorite"),
    path('favorite_list2/', views.FavoriteView2.as_view(), name="favorite2"),
    path('see_favorite2/<int:pk>/', views.seefavorite2, name="see_favorite2"),
    path('favorite_delete2/<int:pk>/', views.FavoriteDeleteView2.as_view(), name="favorite_delete2"),
    path('add_favorite2/<int:post_pk>/', views.add_favorite2, name="add_favorite2"),
    path('get_log/<int:pk>/', views.add_avengers_log, name='get_log'),
    path('log_list/', views.AvengersLogView.as_view(), name='log_list'),
    path('see_avengers_log/<int:pk>/', views.see_avengers_log, name='see_log'),
    path('get_log2/<int:pk>/', views.add_experiences_log, name='get_log2'),
    path('log_list2/', views.ExperiencesLogView.as_view(), name='log_list2'),
    path('see_experiences_log/<int:pk>/', views.see_experiences_log, name='see_log2'),
    path('add_count/<int:pk>/', views.add_count, name='add_count'),
    path('add_count2/<int:pk>/', views.add_count2, name='add_count2'),
    path('report1/<int:subscribe_id>/', views.blacksubscribe1, name='report1'),
    path('report2/<int:pk>/comment/<int:comment_pk>/', views.blacksubscribe2, name='report2'),
    path('report3/<int:pk>/', views.blacksubscribe3, name='report3'),
    path('report4/<int:pk>/', views.blacksubscribe4, name='report4'),
    path('report5/<int:pk>/comment/<int:comment_pk>/', views.blacksubscribe5, name='report5'),
    path('report6/<int:subscribe_id>/', views.blacksubscribe6, name='report6'),
    path('report7/<int:pk>/comment/<int:comment_pk>/', views.blacksubscribe7, name='report7'),
    path('report_list1/', views.ReportView.as_view(), name='report-list01'),
    path('report_list2/', views.ReportView2.as_view(), name='report-list02'),
    path('report_list3/', views.ReportView3.as_view(), name='report-list03'),
    path('report_list4/', views.ReportView4.as_view(), name='report-list04'),
    path('report_list5/', views.ReportView5.as_view(), name='report-list05'),
    path('report_list6/', views.ReportView6.as_view(), name='report-list06'),
    path('report_list7/', views.ReportView7.as_view(), name='report-list07'),
    path('eternal_report_list1/', views.EternalReportView.as_view(), name='eternal_report_list01'),
    path('eternal_report_list2/', views.EternalReportView2.as_view(), name='eternal_report_list02'),
    path('eternal_report_list3/', views.EternalReportView3.as_view(), name='eternal_report_list03'),
    path('eternal_report_list4/', views.EternalReportView4.as_view(), name='eternal_report_list04'),
    path('eternal_report_list5/', views.EternalReportView5.as_view(), name='eternal_report_list05'),
    path('eternal_report_list6/', views.EternalReportView6.as_view(), name='eternal_report_list06'),
    path('eternal_report_list7/', views.EternalReportView7.as_view(), name='eternal_report_list07'),
    path('see_report1/<int:pk>', views.seereport, name='see_report1'),
    path('see_report2/<int:pk>/', views.seereport2, name='see_report2'),
    path('see_report3/<int:pk>/', views.seereport3, name='see_report3'),
    path('delete_report1/<int:pk>/', views.ReportDeleteView.as_view(), name='report_delete1'),
    path('delete_report2/<int:pk>/', views.ReportDeleteView2.as_view(), name='report_delete2'),
    path('delete_report3/<int:pk>/', views.ReportDeleteView3.as_view(), name='report_delete3'),
    path('delete_report4/<int:pk>/', views.ReportDeleteView4.as_view(), name='report_delete4'),
    path('delete_report5/<int:pk>/', views.ReportDeleteView5.as_view(), name='report_delete5'),
    path('delete_report6/<int:pk>/', views.ReportDeleteView6.as_view(), name='report_delete6'),
    path('delete_report7/<int:pk>/', views.ReportDeleteView7.as_view(), name='report_delete7'),
    path('comment/<int:post_pk>/', views.comment_create, name='comment_view'),
    path('comment2/<int:post_pk>/', views.comment_create2, name='comment_view2'),
    path('comment3/<int:post_pk>/', views.comment_create3, name='comment_view3'),
    path('comment4/<int:post_pk>/', views.comment_create4, name='comment_view4'),
    path('reply/<int:comment_pk>/', views.reply_create, name='reply_create'),
    path('reply2/<int:comment_pk>/', views.reply_create2, name='reply_create2'),
    path('reply3/<int:comment_pk>/', views.reply_create3, name='reply_create3'),
    path('reply4/<int:comment_pk>/', views.reply_create4, name='reply_create4'),
    path('all_comment_list/', views.CommentView.as_view(), name='all_comment'),
    path('all_comment_list2/', views.CommentView2.as_view(), name='all_comment2'),
    path('all_comment_list3/', views.CommentView3.as_view(), name='all_comment3'),
    path('comment_delete/<int:pk>/', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('comment_delete2/<int:pk>/', views.CommentDeleteView2.as_view(), name='comment_delete2'),
    path('comment_delete3/<int:pk>/', views.CommentDeleteView3.as_view(), name='comment_delete3'),
    path('community_room/', views.PostListView.as_view(), name='community_room'),
    path('post/new/', views.PostCreateView.as_view(), name='post-create'),
    path('user/<str:username>', views.UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/del/', views.PostDeleteView.as_view(), name='post-delete'),
    path('tag3/<int:pk>/', views.TagDetail3.as_view(), name='tag_detail3'),
    path('user/<str:username>/follows/', views.FollowsListView.as_view(), name='user-follows'),
    path('user/<str:username>/followers/', views.FollowersListView.as_view(), name='user-followers'),
    path('thread_delete/<int:pk>/', views.ThreadDeleteView.as_view(), name='thread_delete'),
    path("dm_to_follow/<int:id>/", views.dm_to_follow, name="dm_to_follow"),
    path("dm_to_follower/<int:id>/", views.dm_to_follower, name="dm_to_follower"),
    path("dm_reply/<int:id>/<int:pk>/", views.dm_reply, name="dm_reply"),
    path('dm_list/', views.DMListView.as_view(), name='dm_list'),
    path('all_dm_list/', views.DMListAllView.as_view(), name='all_dm_list'),
    path('dm_detail/<int:pk>/', views.DMDetailView.as_view(), name='dm_detail'),
    path('dm_is_read/<int:pk>/', views.dm_is_read, name='dm_read'),
    path('dm_send_list/', views.DMSendListView.as_view(), name='dm_send_list'),
    path('dm_all_send_list/', views.DMAllSendListView.as_view(), name='dm_all_send_list'),
    path('dm_send_detail/<int:pk>/', views.DMSendDetailView.as_view(), name='dm_send_detail'),
    path('dm_delete/<int:pk>/', views.DMDeleteView.as_view(), name='dm_delete'),
    path('good/<int:good_id>/', views.good, name='good'),
    path('good2/<int:good_id>/', views.good2, name='good2'),
    path('good3/<int:good_id>/', views.good3, name='good3'),
    path('good4/<int:good_id>/', views.good4, name='good4'),
    path('good5/<int:good_id>/', views.good5, name='good5'),
    path('good6/<int:good_id>/', views.good6, name='good6'),
    path('user_profile/', views.UserProfileView.as_view(), name='profile'),
    path('black_list/', views.BlackListView.as_view(), name='black-list'),
    path('all_black_list/', views.AllBlackListView.as_view(), name='all_black_list'),
    path('log_in_out/', views.AttendanceListView.as_view(), name='log_in_out'),
    path('all_log_in_out/', views.AttendanceAllListView.as_view(), name='all_log_in_out'),
    path('excel_export/', views.excel_export, name='excel_export'),
    path('excel_export2/', views.excel_export2, name='excel_export2'),
    path('excel_export3/', views.excel_export3, name='excel_export3'),
    path('excel_export4/', views.excel_export4, name='excel_export4'),
    path('excel_export5/', views.excel_export5, name='excel_export5'),
    path('excel_export6/', views.excel_export6, name='excel_export6'),
    path('excel_export7/', views.excel_export7, name='excel_export7'),
    path('excel_export8/', views.excel_export8, name='excel_export8'),
    path('excel_export9/', views.excel_export9, name='excel_export9'),
    path('<str:username>/delete/', views.UserDeleteView.as_view(), name='delete'),
    path('user_delete_confirm/', views.DeleteConfirmView.as_view(), name='delete_confirm'),
    path('mental_check/', views.MentalCheckView.as_view(), name='mental_check'),
    path('user_manual/', views.UserManualView.as_view(), name='user_manual'),
    path('user_manual_pc_index/', views.UserManualPCIndex.as_view(), name='manual_pc_index'),
    path('user_manual_pc_index2/', views.UserManualPCIndex2.as_view(), name='manual_pc_index2'),
    path('user_manual_pc_contact/', views.UserManualPCContact.as_view(), name='manual_pc_contact'),
    path('user_manual_pc_contact2/', views.UserManualPCContact2.as_view(), name='manual_pc_contact2'),
    path('user_manual_pc_mentalcheck/', views.UserManualPCMentalCheck.as_view(), name='manual_pc_mentalcheck'),
    path('user_manual_pc_mentalcheck2/', views.UserManualPCMentalCheck2.as_view(), name='manual_pc_mentalcheck2'),
    path('user_manual_pc_searchexpert/', views.UserManualPCSearchLawyer.as_view(), name='manual_pc_searchlawyer'),
    path('user_manual_pc_searchexpert2/', views.UserManualPCSearchLawyer2.as_view(), name='manual_pc_searchlawyer2'),
    path('user_manual_pc_signup/', views.UserManualPCSignUp.as_view(), name='manual_pc_signup'),
    path('user_manual_pc_login/', views.UserManualPCLogIn.as_view(), name='manual_pc_login'),
    path('user_manual_pc_mypage/', views.UserManualPCMyPage.as_view(), name='manual_pc_mypage'),
    path('user_manual_pc_mypage_log/', views.UserManualPCMyPageLog.as_view(), name='manual_pc_mypage_log'),
    path('user_manual_pc_mypage_create/', views.UserManualPCMyPageCreate.as_view(), name='manual_pc_mypage_create'),
    path('user_manual_pc_mypage_favorite/', views.UserManualPCMyPageFavorite.as_view(), name='manual_pc_mypage_favorite'),
    path('user_manual_pc_mypage_detail/', views.UserManualPCMyPageDetail.as_view(), name='manual_pc_mypage_detail'),
    path('user_manual_pc_mypage_update/', views.UserManualPCMyPageUpdate.as_view(), name='manual_pc_mypage_update'),
    path('user_manual_pc_mypage_delete/', views.UserManualPCMyPageDelete.as_view(), name='manual_pc_mypage_delete'),
    path('user_manual_pc_mypage_reply/', views.UserManualPCMyPageReply.as_view(), name='manual_pc_mypage_reply'),
    path('user_manual_pc_mypage_good/', views.UserManualPCMyPageGood.as_view(), name='manual_pc_mypage_good'),
    path('user_manual_pc_mypage_report/', views.UserManualPCMyPageReport.as_view(), name='manual_pc_mypage_report'),
    path('user_manual_pc_mypage_follow/', views.UserManualPCMyPageFollow.as_view(), name='manual_pc_mypage_follow'),
    path('user_manual_pc_everyonespost/', views.UserManualPCEveryonesPost.as_view(), name='manual_pc_everyonespost'),
    path('user_manual_pc_everyonespost_good/', views.UserManualPCEveryonesPostGood.as_view(), name='manual_pc_everyonespost_good'),
    path('user_manual_pc_everyonespost_detail/', views.UserManualPCEveryonesPostDetail.as_view(), name='manual_pc_everyonespost_detail'),
    path('user_manual_pc_everyonespost_detail_follow/', views.UserManualPCEveryonesPostDetailFollow.as_view(), name='manual_pc_everyonespost_detail_follow'),
    path('user_manual_pc_everyonespost_detail_comment/', views.UserManualPCEveryonesPostDetailComment.as_view(), name='manual_pc_everyonespost_detail_comment'),
    path('user_manual_pc_everyonespost_detail_good/', views.UserManualPCEveryonesPostDetailGood.as_view(), name='manual_pc_everyonespost_detail_good'),
    path('user_manual_pc_everyonespost_detail_favorite/', views.UserManualPCEveryonesPostDetailFavorite.as_view(), name='manual_pc_everyonespost_detail_favorite'),
    path('user_manual_pc_everyonespost_detail_report/', views.UserManualPCEveryonesPostDetailReport.as_view(), name='manual_pc_everyonespost_detail_report'),
    path('user_manual_pc_everyonespost_detail_reply/', views.UserManualPCEveryonesPostDetailReply.as_view(), name='manual_pc_everyonespost_detail_reply'),
    path('user_manual_pc_everyonespost_detail_comment_good/', views.UserManualPCEveryonesPostDetailCommentGood.as_view(), name='manual_pc_everyonespost_detail_comment_good'),
    path('user_manual_pc_everyonespost_detail_comment_report/', views.UserManualPCEveryonesPostDetailCommentReport.as_view(), name='manual_pc_everyonespost_detail_comment_report'),
    path('user_manual_pc_everyonespost_detail_comment_follow/', views.UserManualPCEveryonesPostDetailCommentFollow.as_view(), name='manual_pc_everyonespost_detail_comment_follow'),
    path('user_manual_pc_commmunityroom/', views.UserManualPCCommunityRoom.as_view(), name='manual_pc_communityroom'),
    path('user_manual_pc_communityroom_update/', views.UserManualPCCommunityRoomUpdate.as_view(), name='manual_pc_communityroom_update'),
    path('user_manual_pc_communityroom_yourpost/', views.UserManualPCCommunityRoomYourPost.as_view(), name='manual_pc_communityroom_yourpost'),
    path('user_manual_pc_communityroom_yourpost_update/', views.UserManualPCCommunityRoomYourPostUpdate.as_view(), name='manual_pc_communityroom_yourpost_update'),
    path('user_manual_pc_communityroom_yourpost_delete/', views.UserManualPCCommunityRoomYourPostDelete.as_view(), name='manual_pc_communityroom_yourpost_delete'),
    path('user_manual_pc_communityroom_create/', views.UserManualPCCommunityRoomCreate.as_view(), name='manual_pc_communityroom_create'),
    path('user_manual_pc_communityroom_howtofollow/', views.UserManualPCCommunityRoomHowToFollow.as_view(), name='manual_pc_communityroom_howtofollow'),
    path('user_manual_pc_communityroom_follow/', views.UserManualPCCommunityRoomFollow.as_view(), name='manual_pc_communityroom_follow'),
    path('user_manual_pc_communityroom_dmtofollow/', views.UserManualPCCommunityRoomDMToFollow.as_view(), name='manual_pc_communityroom_dmtofollow'),
    path('user_manual_pc_communityroom_follow_gotodetail/', views.UserManualPCCommunityRoomFollowGoToDetail.as_view(), name='manual_pc_communityroom_follow_gotodetail'),
    path('user_manual_pc_communityroom_follow_detail/', views.UserManualPCCommunityRoomFollowDetail.as_view(), name='manual_pc_communityroom_follow_detail'),
    path('user_manual_pc_communityroom_follow_unfollow/', views.UserManualPCCommunityRoomFollowUnfollow.as_view(), name='manual_pc_communityroom_follow_unfollow'),
    path('user_manual_pc_communityroom_follower/', views.UserManualPCCommunityRoomFollower.as_view(), name='manual_pc_communityroom_follower'),
    path('user_manual_pc_communityroom_dmtofollower/', views.UserManualPCCommunityRoomDMToFollower.as_view(), name='manual_pc_communityroom_dmtofollower'),
    path('user_manual_pc_communityroom_follower_gotodetail/', views.UserManualPCCommunityRoomFollowerGoToDetail.as_view(), name='manual_pc_communityroom_follower_gotodetail'),
    path('user_manual_pc_communityroom_follower_detail/', views.UserManualPCCommunityRoomFollowerDetail.as_view(), name='manual_pc_communityroom_follower_detail'),
    path('user_manual_pc_communityroom_follower_follow/', views.UserManualPCCommunityRoomFollowerFollow.as_view(), name='manual_pc_communityroom_follower_follow'),
    path('user_manual_pc_communityroom_dm_sent/', views.UserManualPCCommunityRoomDMSent.as_view(), name='manual_pc_communityroom_dm_sent'),
    path('user_manual_pc_communityroom_dm_sent_filtering/', views.UserManualPCCommunityRoomDMSentFiltering.as_view(), name='manual_pc_communityroom_dm_sent_filtering'),
    path('user_manual_pc_communityroom_dm_sent_detail/', views.UserManualPCCommunityRoomDMSentDetail.as_view(), name='manual_pc_communityroom_dm_sent_detail'),
    path('user_manual_pc_communityroom_dm_sent_report/', views.UserManualPCCommunityRoomDMSentReport.as_view(), name='manual_pc_communityroom_dm_sent_report'),
    path('user_manual_pc_communityroom_dm_send/', views.UserManualPCCommunityRoomDMSend.as_view(), name='manual_pc_communityroom_dm_send'),
    path('user_manual_pc_communityroom_dm_send_filtering/', views.UserManualPCCommunityRoomDMSendFiltering.as_view(), name='manual_pc_communityroom_dm_send_filtering'),
    path('user_manual_pc_communityroom_dm_send_gotodetail/', views.UserManualPCCommunityRoomDMSendGoToDetail.as_view(), name='manual_pc_communityroom_dm_send_gotodetail'),
    path('user_manual_pc_communityroom_dm_send_detail/', views.UserManualPCCommunityRoomDMSendDetail.as_view(), name='manual_pc_communityroom_dm_send_detail'),
    path('user_manual_pc_communityroom_dm_send_detail_delete/', views.UserManualPCCommunityRoomDMSendDetailDelete.as_view(), name='manual_pc_communityroom_dm_send_detail_delete'),
    path('user_manual_pc_communityroom_detail/', views.UserManualPCCommunityRoomDetail.as_view(), name='manual_pc_communityroom_detail'),
    path('user_manual_pc_communityroom_detail_addcomment/', views.UserManualPCCommunityRoomDetailAddComment.as_view(), name='manual_pc_communityroom_detail_addcomment'),
    path('user_manual_pc_communityroom_detail_comment_report/', views.UserManualPCCommunityRoomDetailCommentReport.as_view(), name='manual_pc_communityroom_detail_comment_report'),
    path('user_manual_pc_communityroom_detail_comment_good/', views.UserManualPCCommunityRoomDetailCommentGood.as_view(), name='manual_pc_communityroom_detail_comment_good'),
    path('user_manual_pc_communityroom_detail_comment_follow/', views.UserManualPCCommunityRoomDetailCommentFollow.as_view(), name='manual_pc_communityroom_detail_comment_follow'),
    path('user_manual_pc_communityroom_good/', views.UserManualPCCommunityRoomGood.as_view(), name='manual_pc_communityroom_good'),
    path('user_manual_pc_communityroom_report/', views.UserManualPCCommunityRoomReport.as_view(), name='manual_pc_communityroom_report'),
    path('user_manual_pc_userprofile/', views.UserManualPCUserProfile.as_view(), name='manual_pc_userprofile'),
    path('user_manual_pc_userprofile_changeprofile/', views.UserManualPCUserProfileChangeProfile.as_view(), name='manual_pc_userprofile_changeprofile'),
    path('user_manual_pc_deleteaccount/', views.UserManualPCDeleteAccount.as_view(), name='manual_pc_deleteaccount'),
    path('user_manual_pc_logout/', views.UserManualPCLogOut.as_view(), name='manual_pc_logout'),
    path('user_manual_tablet_index/', views.UserManualTabletIndex.as_view(), name='manual_tablet_index'),
    path('user_manual_tablet_index2/', views.UserManualTabletIndex2.as_view(), name='manual_tablet_index2'),
    path('user_manual_tablet_contact/', views.UserManualTabletContact.as_view(), name='manual_tablet_contact'),
    path('user_manual_tablet_contact2/', views.UserManualTabletContact2.as_view(), name='manual_tablet_contact2'),
    path('user_manual_tablet_mentalcheck/', views.UserManualTabletMentalCheck.as_view(),
         name='manual_tablet_mentalcheck'),
    path('user_manual_tablet_mentalcheck2/', views.UserManualTabletMentalCheck2.as_view(),
         name='manual_tablet_mentalcheck2'),
    path('user_manual_tablet_searchexpert/', views.UserManualTabletSearchLawyer.as_view(),
         name='manual_tablet_searchlawyer'),
    path('user_manual_tablet_searchexpert2/', views.UserManualTabletSearchLawyer2.as_view(),
         name='manual_tablet_searchlawyer2'),
    path('user_manual_tablet_signup/', views.UserManualTabletSignUp.as_view(), name='manual_tablet_signup'),
    path('user_manual_tablet_login/', views.UserManualTabletLogIn.as_view(), name='manual_tablet_login'),
    path('user_manual_tablet_mypage/', views.UserManualTabletMyPage.as_view(), name='manual_tablet_mypage'),
    path('user_manual_tablet_mypage_log/', views.UserManualTabletMyPageLog.as_view(), name='manual_tablet_mypage_log'),
    path('user_manual_tablet_mypage_create/', views.UserManualTabletMyPageCreate.as_view(),
         name='manual_tablet_mypage_create'),
    path('user_manual_tablet_mypage_favorite/', views.UserManualTabletMyPageFavorite.as_view(),
         name='manual_tablet_mypage_favorite'),
    path('user_manual_tablet_mypage_detail/', views.UserManualTabletMyPageDetail.as_view(),
         name='manual_tablet_mypage_detail'),
    path('user_manual_tablet_mypage_update/', views.UserManualTabletMyPageUpdate.as_view(),
         name='manual_tablet_mypage_update'),
    path('user_manual_tablet_mypage_delete/', views.UserManualTabletMyPageDelete.as_view(),
         name='manual_tablet_mypage_delete'),
    path('user_manual_tablet_mypage_reply/', views.UserManualTabletMyPageReply.as_view(),
         name='manual_tablet_mypage_reply'),
    path('user_manual_tablet_mypage_good/', views.UserManualTabletMyPageGood.as_view(),
         name='manual_tablet_mypage_good'),
    path('user_manual_tablet_mypage_report/', views.UserManualTabletMyPageReport.as_view(),
         name='manual_tablet_mypage_report'),
    path('user_manual_tablet_mypage_follow/', views.UserManualTabletMyPageFollow.as_view(),
         name='manual_tablet_mypage_follow'),
    path('user_manual_tablet_everyonespost/', views.UserManualTabletEveryonesPost.as_view(),
         name='manual_tablet_everyonespost'),
    path('user_manual_tablet_everyonespost_good/', views.UserManualTabletEveryonesPostGood.as_view(),
         name='manual_tablet_everyonespost_good'),
    path('user_manual_tablet_everyonespost_detail/', views.UserManualTabletEveryonesPostDetail.as_view(),
         name='manual_tablet_everyonespost_detail'),
    path('user_manual_tablet_everyonespost_detail_follow/', views.UserManualTabletEveryonesPostDetailFollow.as_view(),
         name='manual_tablet_everyonespost_detail_follow'),
    path('user_manual_tablet_everyonespost_detail_comment/', views.UserManualTabletEveryonesPostDetailComment.as_view(),
         name='manual_tablet_everyonespost_detail_comment'),
    path('user_manual_tablet_everyonespost_detail_good/', views.UserManualTabletEveryonesPostDetailGood.as_view(),
         name='manual_tablet_everyonespost_detail_good'),
    path('user_manual_tablet_everyonespost_detail_favorite/',
         views.UserManualTabletEveryonesPostDetailFavorite.as_view(),
         name='manual_tablet_everyonespost_detail_favorite'),
    path('user_manual_tablet_everyonespost_detail_report/', views.UserManualTabletEveryonesPostDetailReport.as_view(),
         name='manual_tablet_everyonespost_detail_report'),
    path('user_manual_tablet_everyonespost_detail_reply/', views.UserManualTabletEveryonesPostDetailReply.as_view(),
         name='manual_tablet_everyonespost_detail_reply'),
    path('user_manual_tablet_everyonespost_detail_comment_good/',
         views.UserManualTabletEveryonesPostDetailCommentGood.as_view(),
         name='manual_tablet_everyonespost_detail_comment_good'),
    path('user_manual_tablet_everyonespost_detail_comment_report/',
         views.UserManualTabletEveryonesPostDetailCommentReport.as_view(),
         name='manual_tablet_everyonespost_detail_comment_report'),
    path('user_manual_tablet_everyonespost_detail_comment_follow/',
         views.UserManualTabletEveryonesPostDetailCommentFollow.as_view(),
         name='manual_tablet_everyonespost_detail_comment_follow'),
    path('user_manual_tablet_commmunityroom/', views.UserManualTabletCommunityRoom.as_view(),
         name='manual_tablet_communityroom'),
    path('user_manual_tablet_communityroom_update/', views.UserManualTabletCommunityRoomUpdate.as_view(),
         name='manual_tablet_communityroom_update'),
    path('user_manual_tablet_communityroom_yourpost/', views.UserManualTabletCommunityRoomYourPost.as_view(),
         name='manual_tablet_communityroom_yourpost'),
    path('user_manual_tablet_communityroom_yourpost_update/',
         views.UserManualTabletCommunityRoomYourPostUpdate.as_view(),
         name='manual_tablet_communityroom_yourpost_update'),
    path('user_manual_tablet_communityroom_yourpost_delete/',
         views.UserManualTabletCommunityRoomYourPostDelete.as_view(),
         name='manual_tablet_communityroom_yourpost_delete'),
    path('user_manual_tablet_communityroom_create/', views.UserManualTabletCommunityRoomCreate.as_view(),
         name='manual_tablet_communityroom_create'),
    path('user_manual_tablet_communityroom_howtofollow/', views.UserManualTabletCommunityRoomHowToFollow.as_view(),
         name='manual_tablet_communityroom_howtofollow'),
    path('user_manual_tablet_communityroom_follow/', views.UserManualTabletCommunityRoomFollow.as_view(),
         name='manual_tablet_communityroom_follow'),
    path('user_manual_tablet_communityroom_dmtofollow/', views.UserManualTabletCommunityRoomDMToFollow.as_view(),
         name='manual_tablet_communityroom_dmtofollow'),
    path('user_manual_tablet_communityroom_follow_gotodetail/',
         views.UserManualTabletCommunityRoomFollowGoToDetail.as_view(),
         name='manual_tablet_communityroom_follow_gotodetail'),
    path('user_manual_tablet_communityroom_follow_detail/', views.UserManualTabletCommunityRoomFollowDetail.as_view(),
         name='manual_tablet_communityroom_follow_detail'),
    path('user_manual_tablet_communityroom_follow_unfollow/',
         views.UserManualTabletCommunityRoomFollowUnfollow.as_view(),
         name='manual_tablet_communityroom_follow_unfollow'),
    path('user_manual_tablet_communityroom_follower/', views.UserManualTabletCommunityRoomFollower.as_view(),
         name='manual_tablet_communityroom_follower'),
    path('user_manual_tablet_communityroom_dmtofollower/', views.UserManualTabletCommunityRoomDMToFollower.as_view(),
         name='manual_tablet_communityroom_dmtofollower'),
    path('user_manual_tablet_communityroom_follower_gotodetail/',
         views.UserManualTabletCommunityRoomFollowerGoToDetail.as_view(),
         name='manual_tablet_communityroom_follower_gotodetail'),
    path('user_manual_tablet_communityroom_follower_detail/',
         views.UserManualTabletCommunityRoomFollowerDetail.as_view(),
         name='manual_tablet_communityroom_follower_detail'),
    path('user_manual_tablet_communityroom_follower_follow/',
         views.UserManualTabletCommunityRoomFollowerFollow.as_view(),
         name='manual_tablet_communityroom_follower_follow'),
    path('user_manual_tablet_communityroom_dm_sent/', views.UserManualTabletCommunityRoomDMSent.as_view(),
         name='manual_tablet_communityroom_dm_sent'),
    path('user_manual_tablet_communityroom_dm_sent_filtering/',
         views.UserManualTabletCommunityRoomDMSentFiltering.as_view(),
         name='manual_tablet_communityroom_dm_sent_filtering'),
    path('user_manual_tablet_communityroom_dm_sent_detail/', views.UserManualTabletCommunityRoomDMSentDetail.as_view(),
         name='manual_tablet_communityroom_dm_sent_detail'),
    path('user_manual_tablet_communityroom_dm_sent_report/', views.UserManualTabletCommunityRoomDMSentReport.as_view(),
         name='manual_tablet_communityroom_dm_sent_report'),
    path('user_manual_tablet_communityroom_dm_send/', views.UserManualTabletCommunityRoomDMSend.as_view(),
         name='manual_tablet_communityroom_dm_send'),
    path('user_manual_tablet_communityroom_dm_send_filtering/',
         views.UserManualTabletCommunityRoomDMSendFiltering.as_view(),
         name='manual_tablet_communityroom_dm_send_filtering'),
    path('user_manual_tablet_communityroom_dm_send_gotodetail/',
         views.UserManualTabletCommunityRoomDMSendGoToDetail.as_view(),
         name='manual_tablet_communityroom_dm_send_gotodetail'),
    path('user_manual_tablet_communityroom_dm_send_detail/', views.UserManualTabletCommunityRoomDMSendDetail.as_view(),
         name='manual_tablet_communityroom_dm_send_detail'),
    path('user_manual_tablet_communityroom_dm_send_detail_delete/',
         views.UserManualTabletCommunityRoomDMSendDetailDelete.as_view(),
         name='manual_tablet_communityroom_dm_send_detail_delete'),
    path('user_manual_tablet_communityroom_detail/', views.UserManualTabletCommunityRoomDetail.as_view(),
         name='manual_tablet_communityroom_detail'),
    path('user_manual_tablet_communityroom_detail_addcomment/',
         views.UserManualTabletCommunityRoomDetailAddComment.as_view(),
         name='manual_tablet_communityroom_detail_addcomment'),
    path('user_manual_tablet_communityroom_detail_comment_report/',
         views.UserManualTabletCommunityRoomDetailCommentReport.as_view(),
         name='manual_tablet_communityroom_detail_comment_report'),
    path('user_manual_tablet_communityroom_detail_comment_good/',
         views.UserManualTabletCommunityRoomDetailCommentGood.as_view(),
         name='manual_tablet_communityroom_detail_comment_good'),
    path('user_manual_tablet_communityroom_detail_comment_follow/',
         views.UserManualTabletCommunityRoomDetailCommentFollow.as_view(),
         name='manual_tablet_communityroom_detail_comment_follow'),
    path('user_manual_tablet_communityroom_good/', views.UserManualTabletCommunityRoomGood.as_view(),
         name='manual_tablet_communityroom_good'),
    path('user_manual_tablet_communityroom_report/', views.UserManualTabletCommunityRoomReport.as_view(),
         name='manual_tablet_communityroom_report'),
    path('user_manual_tablet_userprofile/', views.UserManualTabletUserProfile.as_view(),
         name='manual_tablet_userprofile'),
    path('user_manual_tablet_userprofile_changeprofile/', views.UserManualTabletUserProfileChangeProfile.as_view(),
         name='manual_tablet_userprofile_changeprofile'),
    path('user_manual_tablet_deleteaccount/', views.UserManualTabletDeleteAccount.as_view(),
         name='manual_tablet_deleteaccount'),
    path('user_manual_tablet_logout/', views.UserManualTabletLogOut.as_view(), name='manual_tablet_logout'),
    path('user_manual_sp_index/', views.UserManualSPIndex.as_view(), name='manual_sp_index'),
    path('user_manual_sp_index2/', views.UserManualSPIndex2.as_view(), name='manual_sp_index2'),
    path('user_manual_sp_contact/', views.UserManualSPContact.as_view(), name='manual_sp_contact'),
    path('user_manual_sp_contact2/', views.UserManualSPContact2.as_view(), name='manual_sp_contact2'),
    path('user_manual_sp_mentalcheck/', views.UserManualSPMentalCheck.as_view(), name='manual_sp_mentalcheck'),
    path('user_manual_sp_mentalcheck2/', views.UserManualSPMentalCheck2.as_view(), name='manual_sp_mentalcheck2'),
    path('user_manual_sp_searchexpert/', views.UserManualSPSearchLawyer.as_view(), name='manual_sp_searchlawyer'),
    path('user_manual_sp_searchexpert2/', views.UserManualSPSearchLawyer2.as_view(), name='manual_sp_searchlawyer2'),
    path('user_manual_sp_signup/', views.UserManualSPSignUp.as_view(), name='manual_sp_signup'),
    path('user_manual_sp_login/', views.UserManualSPLogIn.as_view(), name='manual_sp_login'),
    path('user_manual_sp_mypage/', views.UserManualSPMyPage.as_view(), name='manual_sp_mypage'),
    path('user_manual_sp_mypage_log/', views.UserManualSPMyPageLog.as_view(), name='manual_sp_mypage_log'),
    path('user_manual_sp_mypage_create/', views.UserManualSPMyPageCreate.as_view(), name='manual_sp_mypage_create'),
    path('user_manual_sp_mypage_favorite/', views.UserManualSPMyPageFavorite.as_view(),
         name='manual_sp_mypage_favorite'),
    path('user_manual_sp_mypage_detail/', views.UserManualSPMyPageDetail.as_view(), name='manual_sp_mypage_detail'),
    path('user_manual_sp_mypage_update/', views.UserManualSPMyPageUpdate.as_view(), name='manual_sp_mypage_update'),
    path('user_manual_sp_mypage_delete/', views.UserManualSPMyPageDelete.as_view(), name='manual_sp_mypage_delete'),
    path('user_manual_sp_mypage_reply/', views.UserManualSPMyPageReply.as_view(), name='manual_sp_mypage_reply'),
    path('user_manual_sp_mypage_good/', views.UserManualSPMyPageGood.as_view(), name='manual_sp_mypage_good'),
    path('user_manual_sp_mypage_report/', views.UserManualSPMyPageReport.as_view(), name='manual_sp_mypage_report'),
    path('user_manual_sp_mypage_follow/', views.UserManualSPMyPageFollow.as_view(), name='manual_sp_mypage_follow'),
    path('user_manual_sp_everyonespost/', views.UserManualSPEveryonesPost.as_view(), name='manual_sp_everyonespost'),
    path('user_manual_sp_everyonespost_good/', views.UserManualSPEveryonesPostGood.as_view(),
         name='manual_sp_everyonespost_good'),
    path('user_manual_sp_everyonespost_detail/', views.UserManualSPEveryonesPostDetail.as_view(),
         name='manual_sp_everyonespost_detail'),
    path('user_manual_sp_everyonespost_detail_follow/', views.UserManualSPEveryonesPostDetailFollow.as_view(),
         name='manual_sp_everyonespost_detail_follow'),
    path('user_manual_sp_everyonespost_detail_comment/', views.UserManualSPEveryonesPostDetailComment.as_view(),
         name='manual_sp_everyonespost_detail_comment'),
    path('user_manual_sp_everyonespost_detail_good/', views.UserManualSPEveryonesPostDetailGood.as_view(),
         name='manual_sp_everyonespost_detail_good'),
    path('user_manual_sp_everyonespost_detail_favorite/', views.UserManualSPEveryonesPostDetailFavorite.as_view(),
         name='manual_sp_everyonespost_detail_favorite'),
    path('user_manual_sp_everyonespost_detail_report/', views.UserManualSPEveryonesPostDetailReport.as_view(),
         name='manual_sp_everyonespost_detail_report'),
    path('user_manual_sp_everyonespost_detail_reply/', views.UserManualSPEveryonesPostDetailReply.as_view(),
         name='manual_sp_everyonespost_detail_reply'),
    path('user_manual_sp_everyonespost_detail_comment_good/',
         views.UserManualSPEveryonesPostDetailCommentGood.as_view(),
         name='manual_sp_everyonespost_detail_comment_good'),
    path('user_manual_sp_everyonespost_detail_comment_report/',
         views.UserManualSPEveryonesPostDetailCommentReport.as_view(),
         name='manual_sp_everyonespost_detail_comment_report'),
    path('user_manual_sp_everyonespost_detail_comment_follow/',
         views.UserManualSPEveryonesPostDetailCommentFollow.as_view(),
         name='manual_sp_everyonespost_detail_comment_follow'),
    path('user_manual_sp_commmunityroom/', views.UserManualSPCommunityRoom.as_view(), name='manual_sp_communityroom'),
    path('user_manual_sp_communityroom_update/', views.UserManualSPCommunityRoomUpdate.as_view(),
         name='manual_sp_communityroom_update'),
    path('user_manual_sp_communityroom_yourpost/', views.UserManualSPCommunityRoomYourPost.as_view(),
         name='manual_sp_communityroom_yourpost'),
    path('user_manual_sp_communityroom_yourpost_update/', views.UserManualSPCommunityRoomYourPostUpdate.as_view(),
         name='manual_sp_communityroom_yourpost_update'),
    path('user_manual_sp_communityroom_yourpost_delete/', views.UserManualSPCommunityRoomYourPostDelete.as_view(),
         name='manual_sp_communityroom_yourpost_delete'),
    path('user_manual_sp_communityroom_create/', views.UserManualSPCommunityRoomCreate.as_view(),
         name='manual_sp_communityroom_create'),
    path('user_manual_sp_communityroom_howtofollow/', views.UserManualSPCommunityRoomHowToFollow.as_view(),
         name='manual_sp_communityroom_howtofollow'),
    path('user_manual_sp_communityroom_follow/', views.UserManualSPCommunityRoomFollow.as_view(),
         name='manual_sp_communityroom_follow'),
    path('user_manual_sp_communityroom_dmtofollow/', views.UserManualSPCommunityRoomDMToFollow.as_view(),
         name='manual_sp_communityroom_dmtofollow'),
    path('user_manual_sp_communityroom_follow_gotodetail/', views.UserManualSPCommunityRoomFollowGoToDetail.as_view(),
         name='manual_sp_communityroom_follow_gotodetail'),
    path('user_manual_sp_communityroom_follow_detail/', views.UserManualSPCommunityRoomFollowDetail.as_view(),
         name='manual_sp_communityroom_follow_detail'),
    path('user_manual_sp_communityroom_follow_unfollow/', views.UserManualSPCommunityRoomFollowUnfollow.as_view(),
         name='manual_sp_communityroom_follow_unfollow'),
    path('user_manual_sp_communityroom_follower/', views.UserManualSPCommunityRoomFollower.as_view(),
         name='manual_sp_communityroom_follower'),
    path('user_manual_sp_communityroom_dmtofollower/', views.UserManualSPCommunityRoomDMToFollower.as_view(),
         name='manual_sp_communityroom_dmtofollower'),
    path('user_manual_sp_communityroom_follower_gotodetail/',
         views.UserManualSPCommunityRoomFollowerGoToDetail.as_view(),
         name='manual_sp_communityroom_follower_gotodetail'),
    path('user_manual_sp_communityroom_follower_detail/', views.UserManualSPCommunityRoomFollowerDetail.as_view(),
         name='manual_sp_communityroom_follower_detail'),
    path('user_manual_sp_communityroom_follower_follow/', views.UserManualSPCommunityRoomFollowerFollow.as_view(),
         name='manual_sp_communityroom_follower_follow'),
    path('user_manual_sp_communityroom_dm_sent/', views.UserManualSPCommunityRoomDMSent.as_view(),
         name='manual_sp_communityroom_dm_sent'),
    path('user_manual_sp_communityroom_dm_sent_filtering/', views.UserManualSPCommunityRoomDMSentFiltering.as_view(),
         name='manual_sp_communityroom_dm_sent_filtering'),
    path('user_manual_sp_communityroom_dm_sent_detail/', views.UserManualSPCommunityRoomDMSentDetail.as_view(),
         name='manual_sp_communityroom_dm_sent_detail'),
    path('user_manual_sp_communityroom_dm_sent_report/', views.UserManualSPCommunityRoomDMSentReport.as_view(),
         name='manual_sp_communityroom_dm_sent_report'),
    path('user_manual_sp_communityroom_dm_send/', views.UserManualSPCommunityRoomDMSend.as_view(),
         name='manual_sp_communityroom_dm_send'),
    path('user_manual_sp_communityroom_dm_send_filtering/', views.UserManualSPCommunityRoomDMSendFiltering.as_view(),
         name='manual_sp_communityroom_dm_send_filtering'),
    path('user_manual_sp_communityroom_dm_send_gotodetail/', views.UserManualSPCommunityRoomDMSendGoToDetail.as_view(),
         name='manual_sp_communityroom_dm_send_gotodetail'),
    path('user_manual_sp_communityroom_dm_send_detail/', views.UserManualSPCommunityRoomDMSendDetail.as_view(),
         name='manual_sp_communityroom_dm_send_detail'),
    path('user_manual_sp_communityroom_dm_send_detail_delete/',
         views.UserManualSPCommunityRoomDMSendDetailDelete.as_view(),
         name='manual_sp_communityroom_dm_send_detail_delete'),
    path('user_manual_sp_communityroom_detail/', views.UserManualSPCommunityRoomDetail.as_view(),
         name='manual_sp_communityroom_detail'),
    path('user_manual_sp_communityroom_detail_addcomment/', views.UserManualSPCommunityRoomDetailAddComment.as_view(),
         name='manual_sp_communityroom_detail_addcomment'),
    path('user_manual_sp_communityroom_detail_comment_report/',
         views.UserManualSPCommunityRoomDetailCommentReport.as_view(),
         name='manual_sp_communityroom_detail_comment_report'),
    path('user_manual_sp_communityroom_detail_comment_good/',
         views.UserManualSPCommunityRoomDetailCommentGood.as_view(),
         name='manual_sp_communityroom_detail_comment_good'),
    path('user_manual_sp_communityroom_detail_comment_follow/',
         views.UserManualSPCommunityRoomDetailCommentFollow.as_view(),
         name='manual_sp_communityroom_detail_comment_follow'),
    path('user_manual_sp_communityroom_good/', views.UserManualSPCommunityRoomGood.as_view(),
         name='manual_sp_communityroom_good'),
    path('user_manual_sp_communityroom_report/', views.UserManualSPCommunityRoomReport.as_view(),
         name='manual_sp_communityroom_report'),
    path('user_manual_sp_userprofile/', views.UserManualSPUserProfile.as_view(), name='manual_sp_userprofile'),
    path('user_manual_sp_userprofile_changeprofile/', views.UserManualSPUserProfileChangeProfile.as_view(),
         name='manual_sp_userprofile_changeprofile'),
    path('user_manual_sp_deleteaccount/', views.UserManualSPDeleteAccount.as_view(), name='manual_sp_deleteaccount'),
    path('user_manual_sp_logout/', views.UserManualSPLogOut.as_view(), name='manual_sp_logout'),
    path('terms_ob_service/', views.TOSView.as_view(), name='terms_of_service'),
    path('privacy_policy/', views.PolicyView.as_view(), name='privacy_policy'),
    path('search_expert/', views.SearchLawyer.as_view(), name='search_lawyer'),
]